### PR TITLE
CODE RUB: Fix File Name

### PR DESCRIPTION
**Pull request by ahmedanwar100**
File renamed to ProjectionServiceTests.Exceptons.cs File To ProjectionServiceTests.Exceptions.cs

### CODE REVIEW

**Comment by hassanhabib** [comment]
@ahmedanwar100 rename the PR to `CODE RUB: Fix File Name`

**Comment by ahmedanwar100** [comment]
@hassanhabib, can you please review it as I have renamed it.

**Comment by Spectralgo** [comment]
Hi @ahmedanwar100, you should name your branch like this:
image

---

And your commits like that:
image


If you take a look at the commit history or the other branches in this repo, you will see that every one of them are respecting some conventions.

If you want more info on this topic you can take a look at this:
https://github.com/ElbekDeveloper/The-Standard-FAQ#branch-naming-convention

Hope it helps 😉

**Comment by Spectralgo** [comment]
@ahmedanwar100, I would recommend closing this PR and make a whole new branch.

**Comment by ahmedanwar100** [comment]
Ok great

**Pull request closed without merging**
